// Code generated by protoc-gen-go. DO NOT EDIT.
// source: purchase/proto/purchase.proto

/*
Package go_micro_service_purchase is a generated protocol buffer package.

It is generated from these files:
	purchase/proto/purchase.proto

It has these top-level messages:
	PurchaseDetail
	QueryPurchaseRequest
	QueryPurchaseResponse
	QueryPurchaseDetailRequest
*/
package go_micro_service_purchase

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PurchaseDetail struct {
	Id             int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId         int32  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	TotalPrice     int32  `protobuf:"varint,3,opt,name=total_price,json=totalPrice" json:"total_price,omitempty"`
	PurchaseDetail string `protobuf:"bytes,4,opt,name=purchase_detail,json=purchaseDetail" json:"purchase_detail,omitempty"`
	PaidTime       int32  `protobuf:"varint,5,opt,name=paid_time,json=paidTime" json:"paid_time,omitempty"`
	PaidStatus     int32  `protobuf:"varint,6,opt,name=paid_status,json=paidStatus" json:"paid_status,omitempty"`
	Status         int32  `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	CreateTime     int32  `protobuf:"varint,8,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
}

func (m *PurchaseDetail) Reset()                    { *m = PurchaseDetail{} }
func (m *PurchaseDetail) String() string            { return proto.CompactTextString(m) }
func (*PurchaseDetail) ProtoMessage()               {}
func (*PurchaseDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PurchaseDetail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PurchaseDetail) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PurchaseDetail) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *PurchaseDetail) GetPurchaseDetail() string {
	if m != nil {
		return m.PurchaseDetail
	}
	return ""
}

func (m *PurchaseDetail) GetPaidTime() int32 {
	if m != nil {
		return m.PaidTime
	}
	return 0
}

func (m *PurchaseDetail) GetPaidStatus() int32 {
	if m != nil {
		return m.PaidStatus
	}
	return 0
}

func (m *PurchaseDetail) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PurchaseDetail) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type QueryPurchaseRequest struct {
	UserId   int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	StartNum int32 `protobuf:"varint,2,opt,name=start_num,json=startNum" json:"start_num,omitempty"`
	Num      int32 `protobuf:"varint,3,opt,name=num" json:"num,omitempty"`
}

func (m *QueryPurchaseRequest) Reset()                    { *m = QueryPurchaseRequest{} }
func (m *QueryPurchaseRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryPurchaseRequest) ProtoMessage()               {}
func (*QueryPurchaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryPurchaseRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QueryPurchaseRequest) GetStartNum() int32 {
	if m != nil {
		return m.StartNum
	}
	return 0
}

func (m *QueryPurchaseRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type QueryPurchaseResponse struct {
	Purchases []*PurchaseDetail `protobuf:"bytes,1,rep,name=purchases" json:"purchases,omitempty"`
}

func (m *QueryPurchaseResponse) Reset()                    { *m = QueryPurchaseResponse{} }
func (m *QueryPurchaseResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryPurchaseResponse) ProtoMessage()               {}
func (*QueryPurchaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryPurchaseResponse) GetPurchases() []*PurchaseDetail {
	if m != nil {
		return m.Purchases
	}
	return nil
}

type QueryPurchaseDetailRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *QueryPurchaseDetailRequest) Reset()                    { *m = QueryPurchaseDetailRequest{} }
func (m *QueryPurchaseDetailRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryPurchaseDetailRequest) ProtoMessage()               {}
func (*QueryPurchaseDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryPurchaseDetailRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*PurchaseDetail)(nil), "go.micro.service.purchase.PurchaseDetail")
	proto.RegisterType((*QueryPurchaseRequest)(nil), "go.micro.service.purchase.QueryPurchaseRequest")
	proto.RegisterType((*QueryPurchaseResponse)(nil), "go.micro.service.purchase.QueryPurchaseResponse")
	proto.RegisterType((*QueryPurchaseDetailRequest)(nil), "go.micro.service.purchase.QueryPurchaseDetailRequest")
}

func init() { proto.RegisterFile("purchase/proto/purchase.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5d, 0x4b, 0xeb, 0x40,
	0x10, 0x86, 0x9b, 0xf6, 0x34, 0x4d, 0xa6, 0xd0, 0x73, 0xce, 0xfa, 0x15, 0x5b, 0xc4, 0x92, 0x1b,
	0x2b, 0x48, 0x2a, 0x15, 0xff, 0x81, 0x20, 0xde, 0x48, 0x8d, 0x7a, 0x6b, 0x8c, 0xc9, 0xa0, 0x0b,
	0x4d, 0x13, 0xf7, 0x43, 0xec, 0x5f, 0xf7, 0x46, 0xd9, 0xdd, 0x44, 0x4d, 0xa9, 0xd2, 0xbb, 0xcc,
	0xb3, 0x33, 0xef, 0xcc, 0xbc, 0x43, 0x60, 0xaf, 0x90, 0x2c, 0x79, 0x8a, 0x39, 0x8e, 0x0b, 0x96,
	0x8b, 0x7c, 0x5c, 0x85, 0x81, 0x0e, 0xc9, 0xee, 0x63, 0x1e, 0x64, 0x34, 0x61, 0x79, 0xc0, 0x91,
	0xbd, 0xd0, 0x04, 0x83, 0x2a, 0xc1, 0x7f, 0xb3, 0xa0, 0x37, 0x2d, 0x83, 0x33, 0x14, 0x31, 0x9d,
	0x91, 0x1e, 0x34, 0x69, 0xea, 0x59, 0x43, 0x6b, 0xd4, 0x0e, 0x9b, 0x34, 0x25, 0x3b, 0xd0, 0x91,
	0x1c, 0x59, 0x44, 0x53, 0xaf, 0xa9, 0xa1, 0xad, 0xc2, 0x8b, 0x94, 0xec, 0x43, 0x57, 0xe4, 0x22,
	0x9e, 0x45, 0x05, 0xa3, 0x09, 0x7a, 0x2d, 0xfd, 0x08, 0x1a, 0x4d, 0x15, 0x21, 0x07, 0xf0, 0xb7,
	0x6a, 0x14, 0xa5, 0x5a, 0xdc, 0xfb, 0x33, 0xb4, 0x46, 0x6e, 0xd8, 0x2b, 0xea, 0x2d, 0x07, 0xe0,
	0x16, 0x31, 0x4d, 0x23, 0x41, 0x33, 0xf4, 0xda, 0x5a, 0xc7, 0x51, 0xe0, 0x86, 0x66, 0xa8, 0xda,
	0xe8, 0x47, 0x2e, 0x62, 0x21, 0xb9, 0x67, 0x9b, 0x36, 0x0a, 0x5d, 0x6b, 0x42, 0xb6, 0xc1, 0x2e,
	0xdf, 0x3a, 0x66, 0x3e, 0x13, 0xa9, 0xc2, 0x84, 0x61, 0x2c, 0xd0, 0xe8, 0x3a, 0xa6, 0xd0, 0x20,
	0xa5, 0xec, 0xdf, 0xc1, 0xe6, 0x95, 0x44, 0xb6, 0xa8, 0x0c, 0x08, 0xf1, 0x59, 0x22, 0x17, 0xdf,
	0x37, 0xb6, 0x6a, 0x1b, 0x0f, 0xc0, 0xe5, 0x22, 0x66, 0x22, 0x9a, 0xcb, 0xac, 0x34, 0xc3, 0xd1,
	0xe0, 0x52, 0x66, 0xe4, 0x1f, 0xb4, 0x14, 0x36, 0x36, 0xa8, 0x4f, 0xff, 0x1e, 0xb6, 0x96, 0xf4,
	0x79, 0x91, 0xcf, 0x39, 0x92, 0x73, 0x70, 0x2b, 0x07, 0xb8, 0x67, 0x0d, 0x5b, 0xa3, 0xee, 0xe4,
	0x30, 0xf8, 0xf1, 0x48, 0x41, 0xfd, 0x40, 0xe1, 0x57, 0xad, 0x7f, 0x04, 0xfd, 0x5a, 0x87, 0x32,
	0xa3, 0xdc, 0x63, 0xe9, 0x92, 0x93, 0x77, 0x0b, 0x9c, 0x2a, 0x93, 0xbc, 0xc2, 0x7f, 0x5d, 0x7a,
	0xcb, 0x91, 0x7d, 0xc2, 0xf1, 0x2f, 0x53, 0xac, 0xb2, 0xaa, 0x7f, 0xbc, 0x7e, 0x81, 0xd9, 0xdd,
	0x6f, 0x90, 0x05, 0x6c, 0xac, 0x18, 0x9a, 0x9c, 0xae, 0x2b, 0x55, 0x5b, 0xb2, 0xbf, 0xbe, 0x71,
	0x7e, 0xe3, 0xc1, 0xd6, 0x3f, 0xc4, 0xc9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xcb, 0x4c,
	0x48, 0x31, 0x03, 0x00, 0x00,
}
