// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package go_micro_service_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserInfoRequest
	UserInfoResponse
	UserRegisterRequest
	UserRegisterResponse
	UserLoginRequest
	UserLoginResponse
*/
package go_micro_service_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfoRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	UserId   int32  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *UserInfoRequest) Reset()                    { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()               {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfoRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserInfoResponse struct {
	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Telephone string `protobuf:"bytes,4,opt,name=telephone" json:"telephone,omitempty"`
	Age       int32  `protobuf:"varint,5,opt,name=age" json:"age,omitempty"`
	Pwd       string `protobuf:"bytes,6,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *UserInfoResponse) Reset()                    { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()               {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserInfoResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfoResponse) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserInfoResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfoResponse) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserRegisterRequest struct {
	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Telephone string `protobuf:"bytes,3,opt,name=telephone" json:"telephone,omitempty"`
	Age       int32  `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
	Pwd       string `protobuf:"bytes,5,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *UserRegisterRequest) Reset()                    { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()               {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegisterRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserRegisterRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserRegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserRegisterResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UserRegisterResponse) Reset()                    { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()               {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserRegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserLoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Pwd      string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type UserLoginResponse struct {
	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserLoginResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*UserInfoRequest)(nil), "go.micro.service.user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "go.micro.service.user.UserInfoResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "go.micro.service.user.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "go.micro.service.user.UserRegisterResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "go.micro.service.user.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "go.micro.service.user.UserLoginResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x4e, 0xea, 0x40,
	0x10, 0xc6, 0x4f, 0x5b, 0x0a, 0x74, 0xce, 0xc5, 0xe1, 0xac, 0x18, 0x37, 0xa8, 0x09, 0xe9, 0x85,
	0x10, 0x4d, 0x1a, 0x83, 0x4f, 0xe0, 0x15, 0x21, 0x31, 0x5e, 0xd4, 0x78, 0x67, 0x82, 0xb5, 0x8c,
	0x75, 0x13, 0xda, 0xad, 0x9d, 0xa2, 0xef, 0xe0, 0x53, 0xf8, 0x02, 0xbe, 0xa3, 0xd9, 0x2d, 0xa5,
	0xa0, 0xfc, 0xbb, 0xea, 0xce, 0xcc, 0x37, 0xf3, 0xfd, 0x3a, 0xd9, 0x05, 0x98, 0x11, 0x66, 0x5e,
	0x9a, 0xc9, 0x5c, 0xb2, 0xc3, 0x48, 0x7a, 0xb1, 0x08, 0x33, 0xe9, 0x11, 0x66, 0x6f, 0x22, 0x44,
	0x4f, 0x15, 0xdd, 0x21, 0xfc, 0xbb, 0x27, 0xcc, 0x46, 0xc9, 0xb3, 0xf4, 0xf1, 0x75, 0x86, 0x94,
	0xb3, 0x63, 0x70, 0x54, 0x69, 0x9c, 0x04, 0x31, 0x72, 0xa3, 0x6b, 0xf4, 0x1d, 0xbf, 0xa9, 0x12,
	0xb7, 0x41, 0x8c, 0xec, 0x08, 0x1a, 0xba, 0x28, 0x26, 0xdc, 0xec, 0x1a, 0x7d, 0xdb, 0xaf, 0xab,
	0x70, 0x34, 0x71, 0x3f, 0x0d, 0x68, 0x55, 0x93, 0x28, 0x95, 0x09, 0xad, 0xa8, 0xd5, 0x20, 0xab,
	0x54, 0xaf, 0x7a, 0x98, 0x3f, 0x3c, 0xda, 0x60, 0x63, 0x1c, 0x88, 0x29, 0xb7, 0x74, 0xa1, 0x08,
	0xd8, 0x09, 0x38, 0x39, 0x4e, 0x31, 0x7d, 0x91, 0x09, 0xf2, 0x9a, 0xae, 0x54, 0x09, 0xd6, 0x02,
	0x2b, 0x88, 0x90, 0xdb, 0x9a, 0x49, 0x1d, 0x55, 0x26, 0x7d, 0x9f, 0xf0, 0xba, 0x56, 0xaa, 0xa3,
	0xfb, 0x61, 0xc0, 0x81, 0x42, 0xf4, 0x31, 0x12, 0x94, 0xab, 0xef, 0x1e, 0x3f, 0xbc, 0x80, 0x31,
	0x37, 0xc2, 0x58, 0x1b, 0x60, 0x6a, 0xbf, 0x60, 0xec, 0x0a, 0xe6, 0x12, 0xda, 0xab, 0x2c, 0xf3,
	0x95, 0x71, 0x68, 0xc4, 0x48, 0xa4, 0xfa, 0x0b, 0x94, 0x32, 0x74, 0xaf, 0x8b, 0x05, 0xdf, 0xc8,
	0x48, 0x24, 0x7b, 0xa1, 0xcf, 0x4d, 0xcd, 0xca, 0x74, 0x00, 0xff, 0x97, 0x46, 0xcc, 0x1d, 0x4f,
	0x01, 0x04, 0x8d, 0x69, 0x16, 0x86, 0x48, 0xa4, 0x87, 0x34, 0x7d, 0x47, 0xd0, 0x5d, 0x91, 0x18,
	0x7c, 0x99, 0x50, 0x53, 0x4d, 0x0c, 0xa1, 0x59, 0xd2, 0xb2, 0x73, 0x6f, 0xed, 0x75, 0xf2, 0xd6,
	0xac, 0xb7, 0x73, 0xb1, 0x97, 0xb6, 0x80, 0x71, 0xff, 0xb0, 0x07, 0xb0, 0x35, 0x1f, 0xeb, 0x6d,
	0xe9, 0x5b, 0x5e, 0x42, 0xa7, 0xbf, 0x5b, 0xb8, 0x98, 0xfe, 0x08, 0x7f, 0x87, 0x98, 0x97, 0x17,
	0x95, 0x9d, 0x6d, 0x69, 0x5d, 0x7a, 0x13, 0x9d, 0xde, 0x4e, 0x5d, 0xe9, 0xf0, 0x54, 0xd7, 0xef,
	0xed, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x12, 0xcc, 0xf5, 0xfc, 0x7d, 0x03, 0x00, 0x00,
}
